#!/usr/bin/dash
[ -z "$1" ] && printf 'at = atk\nam = artsMod\nn = np damage\np = powerMod\nse = special attack\n\ne.g., bm50 at20 n50' && echo && exit 0
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
OUT_DIR=$RAM_DIR/s4go
[ ! -d "$OUT_DIR" ] && mkdir "$OUT_DIR"
rmNotNum(){ echo "$i" | tr -d -c 0-9'\n';}
for i in "$@"; do
	case "$i" in
		at*)
			rmNotNum "$i" >> "$OUT_DIR"/at &;;
		am*)
			rmNotNum "$i" >> "$OUT_DIR"/am &;;
		bm*)
			rmNotNum "$i" >> "$OUT_DIR"/bm &;;
		qm*)
			rmNotNum "$i" >> "$OUT_DIR"/qm &;;
		n*)
			rmNotNum "$i" >> "$OUT_DIR"/n &;;
		p*)
			rmNotNum "$i" >> "$OUT_DIR"/p &;;
		se*)
			awk -v i="$i" 'BEGIN {print substr(i,3,2)/10}' > "$RAM_DIR"/se &;;
		str*)
			[ -n "$( echo "$i" | grep -F '1')" ] && echo "$i.33333333333" > "$OUT_DIR"/str &;;
	esac
done
sumFile(){ awk '{sum += $1} END {print sum}' "$OUT_DIR/$1";}
ifThenSum(){ [ -s "$OUT_DIR"/"$1" ] && sumFile "$1" >> "$OUT_DIR"/result;}
wait
ifThenSum at &
ifThenSum am &
ifThenSum bm &
ifThenSum qm &
ifThenSum n &
ifThenSum p &
awk 'BEGIN {prod = 1} {if ($1) prod *= $1} END {print prod}' "$OUT_DIR"/result
rm -rf "$OUT_DIR"
