#!/usr/bin/bash
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
spaceToLine=$(echo "$@" | sed 's/\ /\n/g')
OUT_DIR=$RAM_DIR/s4go
[ ! -d "$OUT_DIR" ] && mkdir "$OUT_DIR"
# whichGrep(){ echo "$spaceToLine" | grep -F "$1" | awk '{print $NF}' | tr -d -c 0-9 >> "$RAM_DIR"/s4go/"$2";}
whichGrep(){ echo "$spaceToLine" | grep -F "$1" | tr -d -c 0-9'\n';}
# {
whichGrep 'at' >> "$OUT_DIR"/atkMod
whichGrep 'am' >> "$OUT_DIR"/artsMod
whichGrep 'bm' >> "$OUT_DIR"/busterMod
whichGrep 'qm' >> "$OUT_DIR"/quickMod
whichGrep 'n' >> "$OUT_DIR"/npMod
whichGrep 'p' >> "$OUT_DIR"/npMod 
whichGrep 'se' >> "$OUT_DIR"/seMod 
# whichGrep 'cd' critMod
# whichGrep 'str' sMod
# }
files=$(find "$RAM_DIR/s4go/" -type f 2> /dev/null)
# {
for file in $files; do
	mv "$file" "$file-new"
	awk '{sum += $1} END {print sum}' "$file-new" > "$file"
done
# }
printf "%'d" "$(cat $files | awk 'BEGIN {prod = 1} {if ($1) prod *= $1} END {print prod}')" 
echo ''
rm -rf "$OUT_DIR"
