#!/usr/bin/bash
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
spaceToLine=$(echo "$@" | sed 's/\ /\n/g')
OUT_DIR=$RAM_DIR/s4go
[ ! -d "$OUT_DIR" ] && mkdir "$OUT_DIR"
whichGrep(){ echo "$spaceToLine" | grep -F "$1" | tr -d -c 0-9'\n' >> "$OUT_DIR"/"$2";}
whichGrep 'at' attackMod &
whichGrep 'am' artsMod &
whichGrep 'bm' busterMod &
whichGrep 'qm' quickMod &
whichGrep 'n' pMod &
whichGrep 'p' pMod &
whichGrep 'se' seMod &
wait
files=$(find "$RAM_DIR/s4go/" -type f 2> /dev/null)
for file in $files; do
	mv "$file" "$file.new"
	awk '{sum += $1} END {print sum}' "$file.new" > "$file" &
done
wait
printf "%'d" "$(cat $files | awk 'BEGIN {prod = 1} {if ($1) prod *= $1} END {print prod}')"
{ sleep 1 && rm -rf "$OUT_DIR";} &
