#!/usr/bin/dash
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
servantName=$1
id=$(getInfo id "$servantName")
servantBuffs=$(jq -M -r --argjson ID "$id" '.[] | select (.id==$ID).skills | .[] | .functions | .[] | "\(.funcTargetType) \(.funcTargetTeam) \(.buffs | .[] | .type) \(.buffs | .[] | .name) \(.funcTargetType) \(.buffs | .[] | .type) \(.buffs | .[] | .name) \(.svals | .[].Value)"' "$RAM_SERVANTS")
lineNum=$(echo "$servantBuffs" | wc -l)
i=1
while [ "$lineNum" -lt $i ]; do
	echo "$servantBuffs" | sed -n "$i p"
	i=$((i=i+1))
done
