#!/usr/bin/dash
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
id=$1
servantCard=$( jq --argjson ID "$id" -r -M '.[] | select(.id==$ID) | .noblePhantasms | .[].individuality | .[] | .name' "$RAM_SERVANTS" | /usr/bin/grep -i 'arts\|buster\|quick' | head -n 1 )
echo "$servantCard"
[ "$( echo "$servantCard" | wc -l )" -gt 1  ] && echo "Which one (1, 2, 3)?" && echo "$servantCard" && read -r servantCardFinal && echo "$servantCardFinal"
