#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: getHd <name> <1 or 2 or 3 or 4> <resolution>." && exit 0
if [ -n "$2" ]; then
	whichGrep(){ grep -F "$( sed -n "$2p" "$RAM_SERVANTS_ASC" )";}
	[ -n "$3" ] && resolution=$3
else
	whichGrep(){ grep -F "$( sed -n '4p' "$RAM_SERVANTS_ASC" )";}
fi
res4thum $( getImg -v "$1" | whichGrep "$@" ) "$resolution"
