#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: getInfo <id or class or collectionNo> <name>" && exit 0
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
grepName=$(echo "$@" | cut -d' ' -f2- | sed 's/-/\ /g')
namesNum=$(echo "$grepName" | wc -w)
whichId=5
whichClass=3
whichCollectionNo=6
case $1 in
	'id')
		whichCut(){ cut -d' ' -f"$whichId";};;
	'collectionNo')
		whichCut(){ cut -d' ' -f"$whichCollectionNo";};;
	'className')
		whichCut(){ cut -d' ' -f"$whichClass";};;
esac
case $namesNum in
	'1')
		whichGrep(){ grep -i -F -m 1 "$grepName" "$RAM_LIST_SERVANTS";};;
	'2')
		grepFirst=$(echo "$grepName" | cut -d' ' -f1)
		grepSecond=$(echo "$grepName" | cut -d' ' -f2)
		whichGrep(){ grep -i -F "$grepFirst" "$RAM_LIST_SERVANTS" | grep -i -F -m 1 "$grepSecond";};;
	'3')
		grepFirst=$(echo "$grepName" | cut -d' ' -f1)
		grepSecond=$(echo "$grepName" | cut -d' ' -f2)
		grepThird=$(echo "$grepName" | cut -d' ' -f3)
		whichGrep(){ grep -i -F "$grepFirst" "$RAM_LIST_SERVANTS" | grep -i -F "$grepSecond" | grep -i -F -m 1 "$grepThird";};;
esac
whichGrep "$@" | whichCut
