#!/usr/bin/bash
[ -z "$1" ] && echo "Usage: getImg <toram or store> et cetera" && echo "If not <toram> or <store>, saves to current directory." && exit 0
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
case $1 in
	'-v')
		case $2 in
			'toram')
				servants=$( echo "$@" | cut -d' ' -f3-)
				outDir=$RAM_DIR/;;
			'store')
				servants=$( echo "$@" | cut -d' ' -f3-)
				outDir=$DATA_DIR/;;
			*)
				servants=$( echo "$@" | cut -d' ' -f2-)
				outDir=$PWD/;;
		esac;;
	'toram')
		servants=$( echo "$@" | cut -d' ' -f2-)
		outDir=$RAM_DIR/;;
	'store')
		servants=$( echo "$@" | cut -d' ' -f2-)
		outDir=$DATA_DIR/;;
	*)
		servants=$*
		outDir=$PWD/;;
esac
for servantName in $servants; do
	{ id=$(getInfo id "$servantName"); images=$( jq --argjson ID "$id" -r -M '.[] | select(.id==$ID).extraAssets' "$RAM_SERVANTS" | grep -o 'https.*' | sed -E 's/".?//g')
	{ [ "$1" == '-v' ] && echo "$images" | grep -o '[^/]*$' | sed "s|^|$outDir|g";} &
	[ ! -d "$outDir" ] && mkdir "$outDir"
	for image in $images; do
		{ nohup wget -q -nc -P "$outDir" "$image";} > /dev/null &
	done
	} &
done
