#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: getservantatk name>" && exit 0

. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK

id=$( getservantinfo id "$servantName" )
jq --argjson ID "$id" -r -M '.[] | select(.id==$ID).atkMax' "$RAM_SERVANTS_BASIC"
