#!/usr/bin/bash
[ -z "$1" ] && echo "Usage: getservantimg <toram or store> <name> <name> et cetera" && echo "If not <toram> or <store>, saves to current directory." && exit 0

. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK

[ "$1" == "-v" ] && VERBOSE=true && whereToStore=$2 && whichCut=3 || \
	whereToStore=$1 && whichCut=2

servants=$( echo "$@" | cut -d' ' -f"$whichCut"- )

[ "$whereToStore" == "toram" ] && outDir=$RAM_DIR/ ||
	[ "$whereToStore" != "store" ] && outDir=$PWD

for servantName in $servants; do
	{
	[ -n "$( echo "$servantName" | grep "-" )" ] && spaceServantName=$( echo "$servantName" | sed 's/-/\ /g' )
	id=$( getservantinfo id "$spaceServantName" )
	images=$( jq --argjson ID "$id" -r -M '.[] | select(.id==$ID).extraAssets' "$RAM_SERVANTS_BASIC" | grep -o 'https.*' | sed -E 's/".?//g' )

	[ "$whereToStore" == "store" ] && outDir=$DATA_DIR/$id/

	[ ! -s "$outDir" ] && mkdir "$outDir"
	for image in $images; do
		wget -q -nc -P "$outDir" "$image" &
	done
	[ "$VERBOSE" = true ] && echo "$images" | grep -o '[^/]*$' | sed "s|^|$outDir|g"
	} &
done

