#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: getservanthd <name> <1 or 2 or 3 or 4> <resolution>." && exit 0
if [ -n "$2" ]; then
	whichGrep(){ grep -F "$( sed "$2d" "$RAM_SERVANTS_ASC" )";}
	[ -n "$3" ] && resolution=$3
else
	whichGrep(){ grep -F "$( sed '4!d' "$RAM_SERVANTS_ASC" )";}
fi
res4thum "$( getservantimg -v "$1" | whichGrep "$@" )" "$resolution"
# The number refers to which ascension art you want to upscale, which if not provided will default to all. Resolution is the resolution to which the image is to be upscaled; e.g., 1080 for 1920x1080. If <resolution> is not provided, defaults to 1280x720. If <toram> or <store> is not provided, saves to current directory.
