#!/usr/bin/bash
[ -z "$1" ] && echo "Usage: getservantimg <toram or store> <name> <name> et cetera" && echo "If not <toram> or <store>, saves to current directory." && exit 0

. $HOME/.local/bin/scripts4fgo/GLOBAL

servants=("${@:2}")
if [ "$1" == "store" ]; then
	outDir=$DATA_DIR/$id
elif [ "$1" == "toram" ]; then
	outDir=$RAM_DIR
else
	outDir=$PWD
	servants=("$@")
fi

for servantName in "${servants[@]}"; do
	[ -n "$( echo "$servantName" | grep "-" )" ] && servantName=$( echo "$servantName" | sed 's/-/\ /g' )
	{
	id=$( getservantinfo id "$servantName" )
	images=$( jq --argjson ID "$id" -r -M '.[] | select(.id==$ID).extraAssets' "$RAM_SERVANTS_BASIC" | grep -o 'https.*' | sed -E 's/".?//g' )

	[ ! -s "$outDir" ] && mkdir "$outDir"
	for image in $images; do
		wget -q -nc -P "$outDir" "$image" &
	done
	} &
done
