#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: getservanthd <1 or 2 or 3 or 4> <resolution> <toram or store> <name> <name> et cetera, where number refers to the ascension art you want to upscale and if not provided will default to all and resolution is the resolution to which the image is to be upscaled; e.g., 1080 for 1920x1080. <If <resolution> is not provided, defaults to 1280x720" && echo "If <toram> or <store> is not provided, saves to current directory." && exit 0

if [ "$1" -lt 5 ] && [ "$1" -gt 0 ]; then
	whichSed=$1
	alias whichGrep='grep -F'
	whichToGrep=$( sed "$whichSed!d" "$RAM_SERVANTS_ASC" )
	[ "$2" -eq "$2" ] && resolution=$2 && cutAt=3 || cutAt=2
	whichCut(){ echo "$@" | cut -d' ' -f"$cutAt"- ;}
elif [ "$2" -lt 5 ] && [ "$2" -gt 0 ]; then
	whichSed=$2
	alias whichGrep='grep -F'
	whichToGrep=$( sed "$whichSed!d" "$RAM_SERVANTS_ASC" )
	[ "$1" -eq "$1" ] && resolution=$1 && cutAt=3 || cutAt=2
	whichCut(){ echo "$@" | cut -d' ' -f"$cutAt"- ;}
else
	alias whichGrep=grep
	whichToGrep=$( sed 's|\ |\\\||g' "$RAM_SERVANTS_ASC" | tr '\n' ' ' | sed 's/.$//g' )
	whichCut(){ "$@";} 
fi

res4thum "$( getservantimg -v whichCut | whichGrep "$whichToGrep" )" "$resolution"
