#!/usr/bin/dash
. $HOME/.local/bin/scripts4fgo/GLOBAL
. $HOME/.local/bin/scripts4fgo/GLOBAL_CHECK
id=$(getservantinfo id "$1")
# servantBuffs=$(jq -M -r --argjson ID "$id" '.[] | select (.id==$ID).skills | .[] | .functions | .[] | "\(.funcTargetType) \(.buffs | .[] | .type) \(.svals | .[].Value)"' "$RAM_SERVANTS")
servantBuffs=$(jq -M -r --argjson ID "$id" '.[] | select (.id==$ID).skills | .[] | .functions | .[] | "\(.funcTargetType) \(.buffs | .[] | .type) \(.buffs | .[] | .name) \(.svals | .[].Value)"' "$RAM_SERVANTS")
numOfLines=$(echo "$servantBuffs" | wc -l)
for line in $( seq 10 10 $numOfLines ); do
	echo "$servantBuffs" | sed -n "$line p"
done
