#!/usr/bin/dash
. $HOME/.local/bin/scripts4fgo/GLOBAL
[ -s /usr/bin/rg ] && alias grep="rg"
[ -s /usr/bin/frawk ] && alias awk="frawk"
[ ! -s "$RAM_SERVANTS_BASIC" ] && s4go_setup && s4go_getlist && s4go_getasc && s4go_toram
