#!/usr/bin/dash
[ -z "$1" ] && echo "Usage: res4thumbnail <image> <resolution>" && exit 0
[ -z "$2" ] && resolution=720 || \
	resolution=$2
img=$1
upndownscale(){ waifu2xauto "$1" "$2"
	res "$( cleanpng "$1" )"'-hd.png' "$resolution"
	sq "$( cleanpng "$1" )"'-hd-resized.png'
	echo "$1 has been upscaled $2x.";}
scale=$( getres "$img" | awk -v a="$resolution" '{print int(a/$1 + 0.99)}' )
[ 2 -gt "$scale" ] && echo "'$1' need not be upscaled" && res "$img" "$resolution" && return 0 || \
	[ 5 -gt "$scale" ] && upscale=4 && upndownscale "$img" "$upscale" && return 0 || \
	[ 17 -gt "$scale" ] && upscale=16 && upndownscale "$img" "$upscale" && return 0 || \
	[ 33 -gt "$scale" ] && upscale=32 && upndownscale "$img" "$upscale" && return 0 || \
	upscale=64 && upndownscale "$img" "$upscale"
