#!/usr/bin/dash

[ -z "$1" ] && echo "Usage: getservantid <name>" && exit 0

[ ! -s $RAM_SERVANTS_BASIC ] && s4go_toram

. $HOME/.local/bin/scripts4fgo/GLOBAL

servant_name=$1
[ -n "$( echo "$servant_name" | grep -F "-" )" ] && servant_name=$( echo "$servant_name" | sed 's/-/\ /' ) 

servant_info=$( jq -r -M '.[] | "\(.id) \(.className) \(.name)"' "$RAM_SERVANTS_BASIC" | grep -F -i -m 1 "$servant_name" | cut -d' ' -f1 )
echo "$servant_info"
